### ISSUE TITLE
Resistor values for analog axes

### ISSUE THREAD

**Issue by alastaira** [Danjovic/ControlFreak#1]
Hi there, thanks for this project!

Having found an old (25-30yrs?) Thrustmaster FCS in my mum's loft, this has provided a helpful start in getting some life back into it! I have two questions:

- For the "PC Joystick adaptor", can you explain the purpose of the 120Ω series resistors on the analog lines (and how you arrived at that value)? I've seen various suggested GamePort wiring setups in other projects, but most have used much higher resistors (e.g. 100kΩ in http://www.built-to-spec.com/blog/2009/09/10/using-a-pc-joystick-with-the-arduino/ or 47kΩ in https://www.hackster.io/zachary_fields/thrustmaster-mark-ii-fcs-resurrection-08b793) to pull those lines direct to ground and create a voltage divider with the pot in the joystick. I'm getting quite a lot of "noise" on my analog readings, so I wonder if adjusting that resistor value would help?

- I don't suppose you have any knowledge of the "WCS" throttle add-on (http://www.cyberg8t.com/f2comp/prodwcs.htm) - it appears to let the FCS pass-through it, but also had a 5-pin DIN connector which I think must have gone into a soundcard MIDI interface. Wondering what it would take to retrieve the inputs from that too!

Many thanks,

**Comment by alastaira** [comment]
Ok, so to partially answer my own question (after having actually looked at the code carefully this time!), I see you're taking a different approach - rather than creating a voltage divider and reading a single value from each ADC, you're directly connecting to the pots of the analog axes and reading a whole set of samples in loop (presumeably as it discharges through the capacitor?_ - hence why the wiring looks different!
Still doesn't explain my noisy readings - sadly I fear my pots may have not withstood time :(

**Comment by Danjovic** [comment]
the 120 ohm resistors in series are to protect the microcontroller port when it pulls down the pins to discharge the capacitor and the potentiometer resistance is set to zero.

The circuit uses a temporization network, asmuch as the original PC joystick port works. The timing constant is determined by the series resistance and the capacitor, and the microcontroller measures the time it takes from the moment that the microcontroller release the output to allow the capacitor to charge up to the moment that the voltage reaches the positive voltage threshold of the microcontroller input.

You can make test the circuit with fixed value resistors to check whether the circuit will respond with or without noise. 
With a different wiring it is possible to supply the potentiometer and use the analogRead function to get the voltage readings and maybe reduce some noise by a higher value capacitor (units of uF, like 1u to 10u ).

**Comment by alastaira** [comment]
I understand now - that's great, thanks for the answer.
