### ISSUE TITLE
cant change analog input pins using #define

### ISSUE THREAD

**Issue by Soltinator** [Danjovic/ControlFreak#2]
i tried to change the pins on analog input pins to some other pins on #define and it didnt work.
i poked around the code but i couldn't figure out how sampleAnalogAxes() worked. let alone how to change the pins.
i tried analogRead() but the sampleAnalogAxes() method works so well that i dont want to re write that part.
would you mind if you teach me how that works or how to change pins on that? 
its a bit more advanced then a simple analogRead() to me and im too clueless to figure out by searching alone.

**Comment by Soltinator** [comment]
it turns out that im stupid and im seeing the problem backwards.
i changed the pins and the converter that i made based on your schematics worked perfectly.
i didnt even read your hackaday logs lol. sorry.

**Comment by Soltinator** [comment]
i still dont understand how that bit shift magic is done. so if you dont mind explaining it to me a bit more then what you wrote in your first hackaday log i would be grateful.
only if you dont mind

**Comment by Danjovic** [comment]
The sample of the input is performed once 
`sample = ~PINC;`
the samples are in the 4 least significant bits of the variable **sample**
`sample = [bit7][bit6][bit5][bit4][a1x][a1y][a2x][a2y]`
the state of every input is isolated by the AND operation, starting by the least significant bit and added to the axis counter.
`a2Y+=sample & 1; `
if the state of the bit is LOW nothing is added. On the other hand, if the state of the bit is HIGH the variable is incremented 
then the sample is right shifted, 
`sample>>=1; `
and the next axis input now sits on the bit 0 on the **sample** variable
`sample = [0][bit7][bit6][bit5][bit4][a1x][a1y][a2x]`
and the bit being tested and variable being added correspond to the next axis
` a2X+=sample & 1;`
the process is repeated for the next 2 axes
```
      sample>>=1;
      a1Y+=sample & 1; 
      sample>>=1;
      a1X+=sample & 1;
```
